// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8c7ufDoibVVPBIp8NGmuIh1h6kt9mPY',
    appId: '1:96080183517:web:b718addf3f708fbd275b34',
    messagingSenderId: '96080183517',
    projectId: 'myproject-c3e86',
    authDomain: 'myproject-c3e86.firebaseapp.com',
    storageBucket: 'myproject-c3e86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwf8JXKZLw2YYE9dRqaozke0aqIt94_E',
    appId: '1:96080183517:android:44bf7106c0643db8275b34',
    messagingSenderId: '96080183517',
    projectId: 'myproject-c3e86',
    storageBucket: 'myproject-c3e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9zyBCHpeGpE9m9wUNEpHOGDTD33Q6gZ4',
    appId: '1:96080183517:ios:d157a323642290ca275b34',
    messagingSenderId: '96080183517',
    projectId: 'myproject-c3e86',
    storageBucket: 'myproject-c3e86.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9zyBCHpeGpE9m9wUNEpHOGDTD33Q6gZ4',
    appId: '1:96080183517:ios:d157a323642290ca275b34',
    messagingSenderId: '96080183517',
    projectId: 'myproject-c3e86',
    storageBucket: 'myproject-c3e86.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV8c7ufDoibVVPBIp8NGmuIh1h6kt9mPY',
    appId: '1:96080183517:web:188f1c27c95bbee8275b34',
    messagingSenderId: '96080183517',
    projectId: 'myproject-c3e86',
    authDomain: 'myproject-c3e86.firebaseapp.com',
    storageBucket: 'myproject-c3e86.firebasestorage.app',
  );
}
